config/routes.rb
Quizblog::Application.routes.draw do

  root 'welcome#index'
  devise_for :users
  resources :blog_comments

  get "welcome/index"
  get "welcome/about"
  get "welcome/contact"
  
  resources :blog_entries

  resources :projects

  resources :blogs

  resources :users

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	belongs_to :user
	has_many :blog_entries
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog_entries = @blog.blog_entries
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    if @blog.num_entries == nil
      @blog.num_entries = 0
    end

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render action: 'show', status: :created, location: @blog }
      else
        format.html { render action: 'new' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update

    num_entries = @blog.num_entries

    #num_entries = @blog.num_entries

    num_entries = num_entries + 10

    @blog.num_entries = num_entries

    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:date, :subject, :entry, :user_id, :num_entries)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :entry %><br>
    <%= f.text_area :entry %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1>Listing blogs</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Subject</th>
      <th>Entry</th>
      <th># of Entries</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.date %></td>
        <td><%= blog.subject %></td>
        <td><%= blog.entry %></td>
        <td><%= blog.num_entries %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @blog.date %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @blog.subject %>
</p>

<p>
  <strong>Entry:</strong>
  <%= @blog.entry %>
</p>

<p>
	<strong># of Entries:</strong>
	<%= @blog.num_entries %>
</p>

Here are the blog entries:

<table>
  <thead>
    <tr>
      <th>Entry text</th>
      <th>User</th>
      <th>Subject</th>
      <th>Category</th>
      <th>Blog</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @blog_entries.each do |blog_entry| %>
      <tr>
        <td><%= blog_entry.entry_text %></td>
        <td><%= blog_entry.user_id %></td>
        <td><%= blog_entry.subject %></td>
        <td><%= blog_entry.category %></td>
        <td><%= blog_entry.blog_id %></td>
        <td><%= link_to 'Show', blog_entry %></td>
        <td><%= link_to 'Edit', edit_blog_entry_path(blog_entry) %></td>
        <td><%= link_to 'Destroy', blog_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>