config/routes.rb
Quizblog::Application.routes.draw do

  root 'welcome#index'
  devise_for :users
  resources :blog_comments

  get "welcome/index"
  get "welcome/about"
  get "welcome/contact"
  
  resources :blog_entries

  resources :projects

  resources :blogs

  resources :users

end

app/models/blog_entry.rb
class BlogEntry < ActiveRecord::Base
	belongs_to :blog
	belongs_to :user
	has_many :blog_comments
end

app/controllers/blog_entries_controller.rb
class BlogEntriesController < ApplicationController
  before_action :set_blog_entry, only: [:show, :edit, :update, :destroy]

  # GET /blog_entries
  # GET /blog_entries.json
  def index
    @blog_entries = BlogEntry.all
  end

  # GET /blog_entries/1
  # GET /blog_entries/1.json
  def show
    @blog = @blog_entry.blog
    @user = @blog_entry.user
    # @comments = @blog_entry.blog_comments
    # @comments = @blog_entry.blog_comments

    @last_comment = @blog_entry.blog_comments.last
  end

  # GET /blog_entries/new
  def new
    @blog_entry = BlogEntry.new
  end

  # GET /blog_entries/1/edit
  def edit
  end

  # POST /blog_entries
  # POST /blog_entries.json
  def create
    @blog_entry = BlogEntry.new(blog_entry_params)

    respond_to do |format|
      if @blog_entry.save
        format.html { redirect_to @blog_entry, notice: 'Blog entry was successfully created.' }
        format.json { render action: 'show', status: :created, location: @blog_entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @blog_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_entries/1
  # PATCH/PUT /blog_entries/1.json
  def update
    respond_to do |format|
      if @blog_entry.update(blog_entry_params)
        format.html { redirect_to @blog_entry, notice: 'Blog entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @blog_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_entries/1
  # DELETE /blog_entries/1.json
  def destroy
    @blog_entry.destroy
    respond_to do |format|
      format.html { redirect_to blog_entries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_entry
      @blog_entry = BlogEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_entry_params
      params.require(:blog_entry).permit(:entry_text, :user_id, :subject, :category, :blog_id)
    end
end

app/helpers/blog_entries_helper.rb
module BlogEntriesHelper
end

app/views/blog_entries/_form.html.erb
<%= form_for(@blog_entry) do |f| %>
  <% if @blog_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_entry.errors.count, "error") %> prohibited this blog_entry from being saved:</h2>

      <ul>
      <% @blog_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :entry_text %><br>
    <%= f.text_area :entry_text %>
  </div>
  <div class="field">
    <%= f.collection_select(:user_id, User.all, :id, :full_name) %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :blog_id %><br>
    <%= f.number_field :blog_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_entries/edit.html.erb
<h1>Editing blog_entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_entry %> |
<%= link_to 'Back', blog_entries_path %>

app/views/blog_entries/index.html.erb
<h1>Listing blog_entries</h1>

<table>
  <thead>
    <tr>
      <th>Entry text</th>
      <th>User</th>
      <th>Subject</th>
      <th>Category</th>
      <th>Blog</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @blog_entries.each do |blog_entry| %>
      <tr>
        <td><%= blog_entry.entry_text %></td>
        <td><%= blog_entry.user_id %></td>
        <td><%= blog_entry.subject %></td>
        <td><%= blog_entry.category %></td>
        <td><%= blog_entry.blog_id %></td>
        <td><%= link_to 'Show', blog_entry %></td>
        <td><%= link_to 'Edit', edit_blog_entry_path(blog_entry) %></td>
        <td><%= link_to 'Destroy', blog_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog entry', new_blog_entry_path %>

app/views/blog_entries/new.html.erb
<h1>New blog_entry</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_entries_path %>

app/views/blog_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Entry text:</strong>
  <%= @blog_entry.entry_text %>
</p>

<p>
  <strong>User:</strong>
  <%= @blog_entry.user_id %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @blog_entry.subject %>
</p>

<p>
  <strong>Category:</strong>
  <%= @blog_entry.category %>
</p>

<% if @last_comment != nil %>

<h3><i>Comments:</h3 ><i>
<table>
  <thead>
    <tr>
      <th>Entry text</th>
      <th>User</th>
      <th>Entry date</th>
      
    </tr>
  </thead>

  <tbody>
    
      <tr>
        <td><%= @last_comment.entry_text %></td>
        <td><%= @last_comment.user_id %></td>
        <td><%= @last_comment.entry_date %></td>
      </tr>
    
  </tbody>
</table>

<%= link_to 'Edit', edit_blog_entry_path(@blog_entry) %> |
<%= link_to 'Back', blog_entries_path %>
<% else %>
Sorry, no comments!
<% end %>
<br>