config/routes.rb
Quizblog::Application.routes.draw do

  root 'welcome#index'
  devise_for :users
  resources :blog_comments

  get "welcome/index"
  get "welcome/about"
  get "welcome/contact"
  
  resources :blog_entries

  resources :projects

  resources :blogs

  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :projects
	has_many :blogs
	has_many :blog_comments

#	validates :phone_number, format: { with: /\d{3}-\d{3}-\d{4}/, message: "bad format" }
	def full_name
		"#{first_name} #{last_name}"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    #@users = User.where(first_name: "Todd")
    #or
    #@users = User.where(first_name: ["Russ", "Todd"])

    #and
    #@users = User.where(first_name: "Todd",
    #                    last_name: "Brunsvold")
    
    #greater than
    #@users = User.where("id > 2")  

    num_users = @users.length

    if num_users > 1
      @some_text = "we have #{num_users} users"
      else
      @some_text = "we need more users"

    end 

  end

  # GET /users/1
  # GET /users/1.json
  def show
    @projects = @user.projects
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    # @user.phone_number = number_to_phone(1234554321, area_code: true)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email_address, :phone_number, :twitter_id, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email_address %><br>
    <%= f.email_field :email_address %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.telephone_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :twitter_id %>
    <%= f.text_field :twitter_id %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table class="table table-striped" >
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email address</th>
      <th>Phone Number</th>
      <th>Twitter Username</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email_address %></td>
        <td><%= user.phone_number %></td>
        <td><%= user.twitter_id %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% if @user.first_name == "Todd" %>
 	This is Todd!
<% end %>

<% if @user.first_name != "Todd" %>
	This is not Todd!
<% end %>

<p id="notice"><%= notice %></p>

<p>
  <strong>First Name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email Address:</strong>
  <%= @user.email_address %>
</p>

<p>
  <strong>Phone Number:</strong>
  <%= @user.phone_number %>
</p>

<p>
  <strong>Twitter Username</strong>
  <%= @user.twitter_id %>
</p>
<p>
  <strong>Password</strong>
  <%= @user.password %>
</p>



<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

<h2>List projects!<h2>
<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Due date</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.date %></td>
        <td><%= project.due_date %></td>
        <td><%= project.description %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>